export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const SEARCH_NYT_REQUEST   = 'SEARCH_NYT_REQUEST';
export const SEARCH_NYT_SUCCESS   = 'SEARCH_NYT_SUCCESS';
export const SEARCH_NYT_FAILURE   = 'SEARCH_NYT_FAILURE';
// GET_CRITICS
export const GET_CRITICS_REQUEST  = 'GET_CRITICS_REQUEST';
export const GET_CRITICS_SUCCESS  = 'GET_CRITICS_SUCCESS';
export const GET_CRITICS_FAILURE  = 'GET_CRITICS_FAILURE';
// GET_MOVIE_PICKS
export const GET_MOVIE_PICKS_REQUEST = 'GET_MOVIE_PICKS_REQUEST';
export const GET_MOVIE_PICKS_SUCCESS = 'GET_MOVIE_PICKS_SUCCESS';
export const GET_MOVIE_PICKS_FAILURE = 'GET_MOVIE_PICKS_FAILURE';
export const SEARCH_REVIEWS_REQUEST  = 'SEARCH_REVIEWS_REQUEST';
export const SEARCH_REVIEWS_SUCCESS  = 'SEARCH_REVIEWS_SUCCESS';
export const SEARCH_REVIEWS_FAILURE  = 'SEARCH_REVIEWS_FAILURE';
export const CLEAR_ERRORS         = 'CLEAR_ERRORS';
