export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const SEARCH_NYT_REQUEST   = 'SEARCH_NYT_REQUEST';
export const SEARCH_NYT_SUCCESS   = 'SEARCH_NYT_SUCCESS';
export const SEARCH_NYT_FAILURE   = 'SEARCH_NYT_FAILURE';
